from edit_this import skill_prices


def transform_to_powers_of_two(s_d):
    transformed_dict = {}
    for index, (skill, hex_value) in enumerate(s_d.items()):
        new_value = 2 ** (index + 1)
        transformed_dict[skill] = hex(new_value)[2:].upper()  # Convert to hex and remove '0x'
    return transformed_dict


skill_prices_dict = {row[0]: int(row[1]) for row in skill_prices}

# DON'T MESS WITH THESE DICTIONARY THEY KEEP TRACK OF HEX VALUES
skills_dict = {
    'HP +5': '01',
    'Strength +2': '02',
    'Magic +2': '03',
    'Skill +2': '04',
    'Speed +2': '05',
    'Luck +4': '06',
    'Defense +2': '07',
    'Resistance +2': '08',
    'Movement +1': '09',
    'Draconic Hex': '0A',
    'Seal Strength': '0B',
    'Seal Magic': '0C',
    'Seal Speed': '0D',
    'Seal Defense': '0E',
    'Seal Resistance': '0F',
    'Rally Strength': '10',
    'Rally Magic': '11',
    'Rally Skill': '12',
    'Rally Speed': '13',
    'Rally Luck': '14',
    'Rally Defense': '15',
    'Rally Resistance': '16',
    'Rally Movement': '17',
    'Inspiring Song': '18',
    'Lethality': '19',
    'Aether': '1A',
    'Astra': '1B',
    'Dragon Fang': '1C',
    'Sol': '1D',
    'Luna': '1E',
    'Rend Heaven': '1F',
    'Vengeance': '20',
    'Pavise': '21',
    'Aegis': '22',
    'Dragon Ward': '23',
    'Miracle': '24',
    'Counter': '25',
    'Countermagic': '26',
    'Vantage': '27',
    'Beastbane': '28',
    'Golembane': '29',
    'Nohrian Trust': '2A',
    'Hoshidan Unity': '2B',
    'Shelter': '2C',
    'Shove': '2D',
    'Lunge': '2E',
    'Swap': '2F',
    'Replicate': '30',
    'Quick Draw': '31',
    'Strong Riposte': '32',
    'Elbow Room': '33',
    'Natural Cover': '34',
    'Even Handed': '35',
    'Odd Shaped': '36',
    'Life and Death': '37',
    'Spendthrift': '38',
    'Duelist\'s Blow': '39',
    'Darting Blow': '3A',
    'Death Blow': '3B',
    'Certain Blow': '3C',
    'Armored Blow': '3D',
    'Warding Blow': '3E',
    'Trample': '3F',
    'Wary Fighter': '40',
    'Swordfaire': '41',
    'Lancefaire': '42',
    'Axefaire': '43',
    'Shurikenfaire': '44',
    'Bowfaire': '45',
    'Tomefaire': '46',
    'Defender': '47',
    'Charm': '48',
    'Demoiselle': '49',
    'Gentilhomme': '4A',
    'Inspiration': '4B',
    'Malefic Aura': '4C',
    'Voice of Peace': '4D',
    'Foreign Princess': '4E',
    'Swordbreaker': '4F',
    'Lancebreaker': '50',
    'Axebreaker': '51',
    'Shurikenbreaker': '52',
    'Bowbreaker': '53',
    'Tomebreaker': '54',
    'Gamble': '55',
    'Underdog': '56',
    'Lucky Seven': '57',
    'Air Superiority': '58',
    'Heartseeker': '59',
    'Quixotic': '5A',
    'Good Fortune': '5B',
    'Relief': '5C',
    'Camaraderie': '5D',
    'Renewal': '5E',
    'Even Better': '5F',
    'Better Odds': '60',
    'Amaterasu': '61',
    'Lifetaker': '62',
    'Potent Potion': '63',
    'Live to Serve': '64',
    'Poison Strike': '65',
    'Savage Blow': '66',
    'Grisly Wound': '67',
    'Salvage Blow': '68',
    'Profiteer': '69',
    'Nobility': '6A',
    'Future Sight': '6B',
    'Aptitude': '6C',
    'Quick Salve': '6D',
    'Galeforce': '6E',
    'Pass': '6F',
    'Locktouch': '70',
    'Brynhildr': '71',
    'Dragonskin': '72',
    'Divine Shield': '73',
    'Hit/Avo +10': '74',
    'Hit/Avo +20': '75',
    'Resist Status': '76',
    'Immune Status': '77',
    'Bold Stance': '78',
    'Point Blank': '79',
    'Winged Shield': '7A',
    'Void Curse': '7B',
    'Self-Destruct': '7C',
    'Staff Savant': '7D',
    'Immobilize': '7E',
    'Inevitable End': '7F',
    'Even Keel': '80',
    'Iron Will': '81',
    'Clarity': '82',
    'Aggressor': '83',
    'Dual Striker': '84',
    'Awakening': '85',
    'Tactical Advice': '86',
    'Solidarity': '87',
    'Ignis': '88',
    'Rally Spectrum': '89',
    'Paragon': '8A',
    'Armor Shield': '8B',
    'Beast Shield': '8C',
    'Shadowgift': '8D',
    'Strengthtaker': '8E',
    'Magictaker': '8F',
    'Skilltaker': '90',
    'Speedtaker': '91',
    'Lucktaker': '92',
    'Defensetaker': '93',
    'Resistancetaker': '94',
    'Survey': '95',
    'Opportunity Shot': '96',
    'Rifled Barrel': '97',
    'Surefooted': '98',
    'Witch\'s Brew': '99',
    'Warp': '9A',
    'Toxic Brew': '9B',
    'Dancing Blade': '9C',
    'Dual Guardsman': '9D',
    'Heavy Blade': '9E',
    'Veteran Intuition': '9F',
    'Supportive': 'A0',
    'Forceful Partner': 'A1',
    'Devoted Partner': 'A2',
    'Evasive Partner': 'A3',
    'Fiery Blood': 'A4',
    'Miraculous Save': 'A5',
    'Healing Descant': 'A6',
    'Quiet Strength': 'A7',
    'Fearsome Blow': 'A8',
    'Perfectionist': 'A9',
    'Vow of Friendship': 'AA',
    'Pyrotechnics': 'AB',
    'Capture': 'AC',
    'Rallying Cry': 'AD',
    'Divine Retribution': 'AE',
    'Optimistic': 'AF',
    'Pride': 'B0',
    'Nohr Enmity': 'B1',
    'Triple Threat': 'B2',
    'Competitive': 'B3',
    'Shuriken Mastery': 'B4',
    'Morbid Celebration': 'B5',
    'Reciprocity': 'B6',
    'Bushido': 'B7',
    'In Extremis': 'B8',
    'Highwayman': 'B9',
    'Lily\'s Poise': 'BA',
    'Misfortunate': 'BB',
    'Puissance': 'BC',
    'Aching Blood': 'BD',
    'Kidnap': 'BE',
    'Countercurse': 'BF',
    'Rose\'s Thorns': 'C0',
    'Fierce Rival': 'C1',
    'Opportunist': 'C2',
    'Fancy Footwork': 'C3',
    'Bloodthirst': 'C4',
    'Fierce Mien': 'C5',
    'Unmask': 'C6',
    'Pragmatic': 'C7',
    'Collector': 'C8',
    'Chivalry': 'C9',
    'Peacebringer': 'CA',
    'Wind Disciple': 'CB',
    'Perspicacious': 'CC',
    'Icy Blood': 'CD',
    'Forager': 'CE',
    'Draconic Heir': 'CF',
    'Born Steward': 'D0',
    'Perfect Pitch': 'D1',
    'Mischievous': 'D2',
    'Lucky Charm': 'D3',
    'Noble Cause': 'D4',
    'Optimist': 'D5',
    'Sweet Tooth': 'D6',
    'Playthings': 'D7',
    'Calm': 'D8',
    'Haiku': 'D9',
    'Prodigy': 'DA',
    'Vendetta': 'DB',
    'Gallant': 'DC',
    'Guarded Bravery': 'DD',
    'Fierce Counter': 'DE',
    'Goody Basket': 'DF',
    'Fortunate Son': 'E0',
    'Bibliophile': 'E1',
    'Sisterhood': 'E2',
    'Daydream': 'E3',
    'Make A Killing': 'E4'
}
skill_learn_values = transform_to_powers_of_two(skills_dict)
skills_dict['None'] = '00'
skill_learn_values['None'] = '0'


def calculate_skills_value(skills):
    """
    This function takes a list of skills and calculates the hex value of all the skills added.
    Makes sure to exclude personals, as those can't be part of the learned skill list.
    :param skills: List of skills
    :return: String. Hex value of the skills added together
    """
    total_value = 1
    for skill in skills:
        if int(skills_dict[skill], 16) < 160 and int(skills_dict[skill], 16) != 0:
            total_value += int(skill_learn_values[skill], 16)  # Convert hex string to integer and add to total
    # print(hex(total_value)[2:])
    return hex(total_value)[2:]  # Convert back to hex string
